### ISSUE TITLE
What compiler/environment is required to build this source?

### ISSUE THREAD

**Issue by WebsiteInc** [drmortalwombat/zombies#1]
What compiler/environment is required to build this source?
Thanks!!

**Comment by drmortalwombat** [comment]
You need the oscar64 compiler https://github.com/drmortalwombat/oscar64

You can build oscar64 with:
On Linux (and probably Mac Os) the first choice would be gcc.
On Windows I would recommend Visual Studio 2022 or gcc with WSL (Linux subsystem on Windows)
